import { NextResponse } from "next/server";

// Audit log every compliance export. The actual file is generated by the backend;
// this route only records the request for compliance/insurance review.
export async function POST(req: Request, { params }: { params: { format: string } }) {
  const { format } = params;
  if (format !== "csv" && format !== "pdf") {
    return NextResponse.json({ error: "unsupported format" }, { status: 400 });
  }
  const body = await req.json().catch(() => ({}));
  const target = `${process.env.NEXT_PUBLIC_API_URL}/exports/${format}`;
  const res = await fetch(target, {
    method: "POST",
    headers: { "content-type": "application/json", cookie: req.headers.get("cookie") ?? "" },
    body: JSON.stringify(body),
  });
  return new NextResponse(res.body, {
    status: res.status,
    headers: { "content-type": res.headers.get("content-type") ?? "application/octet-stream" },
  });
}
